// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
using PhoneStore.Domain.DataContext;

#nullable disable

namespace PhoneStore.Domain.Migrations
=======
using PhoneStore.Infrastructure.DataContext;

#nullable disable

namespace PhoneStore.Infrastructure.Migrations
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhoneStore.Domain.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
                    b.Property<Guid>("CartId")
=======
                    b.Property<Guid?>("CartId")
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("EmailConfirmed")
<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");
=======
                        .HasMaxLength(256)
                        .HasColumnType("bit");

                    b.Property<byte[]>("Img")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
=======
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
                    b.HasIndex("CartId")
                        .IsUnique();

                    b.ToTable("Account");
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.AccountRole", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccountId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AccountRole");
=======
                    b.HasIndex("CartId");

                    b.HasIndex("RoleId");

                    b.ToTable("Account");
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.Capacity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CapacityName")
                        .IsRequired()
<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
                        .HasColumnType("nvarchar(max)");
=======
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
                    b.ToTable("Capacity");
=======
                    b.ToTable("Capacities");
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
                    b.HasKey("Id");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

=======
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CardItem");
=======
                    b.ToTable("Cart");
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
=======
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs

                    b.Property<int>("StatusProduct")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PriceAtTime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
=======
                    b.Property<int?>("BuyCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("uniqueidentifier");

>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsPromoted")
                        .HasColumnType("bit");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
=======
                    b.HasIndex("CartId");

>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
                    b.ToTable("Product");
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.ProductColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorName")
                        .IsRequired()
<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
                        .HasColumnType("nvarchar(max)");
=======
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Color");
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");
=======
                    b.Property<byte[]>("Img")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uniqueidentifier");

<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
                    b.Property<Guid?>("ProductVariantsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductVariantsId");
=======
                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId")
                        .IsUnique();
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs

                    b.ToTable("ProductImage");
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.ProductVariants", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapacityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid?>("ProductColorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
=======
                    b.Property<Guid>("ProductImageId")
                        .HasColumnType("uniqueidentifier");

>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
                    b.HasIndex("CapacityId");
=======
                    b.HasIndex("CapacityId")
                        .IsUnique();
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs

                    b.HasIndex("ProductColorId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariant");
                });

<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("PhoneStore.Domain.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
=======
            modelBuilder.Entity("PhoneStore.Domain.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
=======
                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExpire")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.Review", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");
=======
                    b.HasKey("AccountId", "ProductId");
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs

                    b.HasIndex("ProductId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .IsRequired()
<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
                        .HasColumnType("nvarchar(max)");
=======
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.Account", b =>
                {
                    b.HasOne("PhoneStore.Domain.Models.Cart", "Cart")
<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
                        .WithOne("Account")
                        .HasForeignKey("PhoneStore.Domain.Models.Account", "CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.AccountRole", b =>
                {
                    b.HasOne("PhoneStore.Domain.Models.Account", "Account")
                        .WithMany("AccountRoles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhoneStore.Domain.Models.Role", "Role")
                        .WithMany("AccountRoles")
=======
                        .WithMany("Account")
                        .HasForeignKey("CartId");

                    b.HasOne("PhoneStore.Domain.Models.Role", "Role")
                        .WithMany("Accounts")
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
                    b.Navigation("Account");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.CartItem", b =>
                {
                    b.HasOne("PhoneStore.Domain.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhoneStore.Domain.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
=======
                    b.Navigation("Cart");

                    b.Navigation("Role");
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.Order", b =>
                {
                    b.HasOne("PhoneStore.Domain.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.OrderItem", b =>
                {
                    b.HasOne("PhoneStore.Domain.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhoneStore.Domain.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
                        .OnDelete(DeleteBehavior.Cascade)
=======
                        .OnDelete(DeleteBehavior.Restrict)
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.Product", b =>
                {
                    b.HasOne("PhoneStore.Domain.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
=======
                    b.HasOne("PhoneStore.Domain.Models.Cart", null)
                        .WithMany("Product")
                        .HasForeignKey("CartId");

>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
                    b.Navigation("Brand");
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.ProductImage", b =>
                {
<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
                    b.HasOne("PhoneStore.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhoneStore.Domain.Models.ProductVariants", "ProductVariants")
                        .WithMany()
                        .HasForeignKey("ProductVariantsId");

                    b.Navigation("Product");
=======
                    b.HasOne("PhoneStore.Domain.Models.ProductVariants", "ProductVariants")
                        .WithOne("ProductImages")
                        .HasForeignKey("PhoneStore.Domain.Models.ProductImage", "ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs

                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.ProductVariants", b =>
                {
                    b.HasOne("PhoneStore.Domain.Models.Capacity", "Capacity")
<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
                        .WithMany()
                        .HasForeignKey("CapacityId")
=======
                        .WithOne("ProductVariant")
                        .HasForeignKey("PhoneStore.Domain.Models.ProductVariants", "CapacityId")
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhoneStore.Domain.Models.ProductColor", "ProductColor")
                        .WithMany()
                        .HasForeignKey("ProductColorId");

                    b.HasOne("PhoneStore.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capacity");

                    b.Navigation("Product");

                    b.Navigation("ProductColor");
                });

<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
=======
            modelBuilder.Entity("PhoneStore.Domain.Models.RefreshToken", b =>
                {
                    b.HasOne("PhoneStore.Domain.Models.Account", "Account")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("PhoneStore.Domain.Models.Review", b =>
                {
                    b.HasOne("PhoneStore.Domain.Models.Account", "Account")
                        .WithMany("AccountReview")
                        .HasForeignKey("AccountId")
<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
                        .OnDelete(DeleteBehavior.Cascade)
=======
                        .OnDelete(DeleteBehavior.Restrict)
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
                        .IsRequired();

                    b.HasOne("PhoneStore.Domain.Models.Product", "Product")
                        .WithMany("ProductReview")
                        .HasForeignKey("ProductId")
<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
                        .OnDelete(DeleteBehavior.Cascade)
=======
                        .OnDelete(DeleteBehavior.Restrict)
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.Account", b =>
                {
                    b.Navigation("AccountReview");

<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
                    b.Navigation("AccountRoles");
=======
                    b.Navigation("RefreshTokens");
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
=======
            modelBuilder.Entity("PhoneStore.Domain.Models.Capacity", b =>
                {
                    b.Navigation("ProductVariant");
                });

>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("PhoneStore.Domain.Models.Cart", b =>
                {
                    b.Navigation("Account");

<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
                    b.Navigation("CartItems");
=======
                    b.Navigation("Product");
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.Product", b =>
                {
<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
                    b.Navigation("CartItems");

=======
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
                    b.Navigation("OrderItems");

                    b.Navigation("ProductReview");
                });

<<<<<<< HEAD:PhoneStore.Domain/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("PhoneStore.Domain.Models.Role", b =>
                {
                    b.Navigation("AccountRoles");
=======
            modelBuilder.Entity("PhoneStore.Domain.Models.ProductVariants", b =>
                {
                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("PhoneStore.Domain.Models.Role", b =>
                {
                    b.Navigation("Accounts");
>>>>>>> 41a6b7ead206b44440065dbb6e01b8e681c23bbf:Backend/PhoneStore.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
                });
#pragma warning restore 612, 618
        }
    }
}
